### PR TITLE
Update Polish translation for v0.6.1

### PR DESCRIPTION
**Pull request by suve**
This PR updates the Polish translation for the upcoming 0.6.1 release. Fixes issue #91.

### CODE REVIEW

**Review by alemart — COMMENTED** [review]
Thank you, @suve !

Regarding the bitmap font, which letters do you need for Polish?

**Comment by suve** [comment]
```
CLEARED_LINE1               "UKONCZONO"
```
This should be `UKOŃCZONO`, with an `Ń` - [U+0143](https://symbl.cc/en/0143/) Latin Capital Letter N With Acute.
```
CLEARED_POWER               "Bonus za energie"
```
This should be `Bonus za energię`, with an `ę` - [U+0119](https://symbl.cc/en/0119/) Latin Small Letter E With Ogonek.
```
PAUSE_EXIT                  "WYJDZ"
```
This should be `WYJDŹ`, with a `Ź` - [U+0179](https://symbl.cc/en/0179/) Latin Capital Letter Z With Acute.

**Comment by alemart** [comment]
Do you need more letters than those in general?

**Comment by alemart** [comment]
This is the current character set:

good_neighbors

**Comment by suve** [comment]
Most of the menu texts are rendered from TTF fonts, right? The only texts using the bitmap font are the ones I posted above. Looking at the `good_neighbours` font, all three letters which we'd currently require are missing.

Unless your question is "which letters would need to be added to fully support Polish", in which case the Wikipedia article on Polish alphabet contains [a handy listing](https://en.wikipedia.org/wiki/Polish_alphabet#Computer_encoding).

**Review by alemart — CHANGES_REQUESTED** [review]
I have just added all the letters - see 24d1a83ade758521e5b9158742faa7f8f3c3ad27. In addition, the title screen is now using the bitmap font. Note that the large font only has Ń. Would you review the translation after this update?

good_neighbors

> Unless your question is "which letters would need to be added to fully support Polish", in which case the Wikipedia article on Polish alphabet contains [a handy listing](https://en.wikipedia.org/wiki/Polish_alphabet#Computer_encoding).

That was very handy, thanks!

**Comment by alemart** [comment]
@suve Are `CLEARED_POWER` and `PAUSE_EXIT` the only required changes?

**Comment by suve** [comment]
Per my earlier comment, `CLEARED_LINE1` should also be changed.

I am currently away from my dev machine and thus unable to review the translation in-game.

**Comment by alemart** [comment]
> I am currently away from my dev machine and thus unable to review the translation in-game.

Well, let's just change the three strings for now.

**Pull request merged**
