### PR TITLE
Update Esperanto translation

### PR DESCRIPTION
**Pull request by jorgesumle**
Solves #92 

100% translated into Esperanto now. I haven't tested if everything is OK in-game. If there aren't any issues with some texts being too long or things like that, it can be merged.

### CODE REVIEW

**Review by alemart — COMMENTED** [review]
Hi @jorgesumle,

Would you access the developer mode to test everything in-game? The developer mode grants you easy access to various scenes of the game. To activate it, simply go to the options screen, highlight stage select and press right 3 times as follows:

https://github.com/alemart/opensurge/assets/221477/a8324a1f-f631-43fa-acfb-190f31a7ffab

**Comment by jorgesumle** [comment]
I got:

```opensurge: error while loading shared libraries: libsurgescript.so.0.6.0: cannot open shared object file: No such file or directory```

Having issues compiling the game:

```
09:54 $ ls
CMakeCache.txt        libsurgescript.so        src
CMakeFiles            libsurgescript.so.0.6.0  surgescript
cmake_install.cmake   libsurgescript-static.a  surgescript.pc
install_manifest.txt  Makefile                 surgescript-static.pc
✔ ~/Repositorios/surgescript/build [master|✔] 
09:54 $ surgescript 
surgescript: error while loading shared libraries: libsurgescript.so.0.6.0: cannot open shared object file: No such file or directory
```

**Comment by alemart** [comment]
Hi @jorgesumle,

You can set standard paths on CMake, use `LD_LIBRARY_PATH` for non-standard paths, or enable only static linking when compiling SurgeScript. If compiling is taking too much time, you can also run [this development build](https://download.tuxfamily.org/opensurge/builds/opensurge-0.6.1.0-windows-20240313-dev.zip) using wine.

**Comment by jorgesumle** [comment]
Captura de pantalla de 2024-03-24 04-39-16

It should say "LUDI EN PO**Ŝ**TELEFONO", but it seems some special characters are not shown there. I had to change it to posxtelefono (see <https://eo.wikipedia.org/wiki/X-sistemo>). I hope you can fix this issue with special characters in an upcoming release.

**Comment by alemart** [comment]
@jorgesumle It is fixed - see c33a933fdf81680d0a40c028637f99b5a41521ba. What other characters do you need for Esperanto? This is the current set:

good_neighbors

eo

**Comment by jorgesumle** [comment]
> What other characters do you need for Esperanto?

These are all special characters needed: Ĉ Ĝ Ĥ Ĵ Ŝ Ŭ ĉ ĥ ĵ ŝ ŭ

I saw you added Ŝ and ŝ, so I guess that adding the rest won't be hard :+1:

**Comment by alemart** [comment]
I have added the letters - see b0321c73e218239c05e45dbc2ee974a501dc173b. Would you review your translation now that we have them?

**Review by alemart — APPROVED** [review]
This is great! Dankon!

**Pull request merged**
