### PR TITLE
Update bosnian.lng

### PR DESCRIPTION
**Pull request by SecularSteve**
Updated, as requested.

### CODE REVIEW

**Review by alemart — CHANGES_REQUESTED** [review]
Thanks!

How can the pause screen be fixed?

bosnian

**Comment by SecularSteve** [comment]
Just replace "IZAĐI" with "IZADI" or "IZADJI" as a workaround.

**Review by alemart — CHANGES_REQUESTED** [review]
Can you change PAUSE_RESTART so that it stays within the boundaries?

In addition, we have new characters in that smaller bitmap font, including common Cyrillic letters. Which new letters do you need to make your translations work without adaptations? Are these sufficient? čČćĆžŽđĐšŠ

good_neighbors

**Review by alemart — APPROVED** [review]
Looks better, thanks!

Captura de tela_2024-03-24_20-22-27

**Pull request merged**
