### PR TITLE
Translate Android metadata to french

### PR DESCRIPTION
**Pull request by Stilic**

### CODE REVIEW

**Review by alemart — CHANGES_REQUESTED** [review]
Hi @Stilic,

Please adjust the title. It's too long.

Keep in mind the limits I mentioned earlier:
* short_description.txt: max 80 chars. If translating is not possible, write an approximate translation that fits the limit (this is ok :+1:)
* :point_right:  title.txt: max 30 chars. If translating is not possible, leave it unstranslated

**Comment by alemart** [comment]
Maybe this?
```
OpenSurge: moteur de jeu rétro
```

**Comment by Stilic** [comment]
> Maybe this?
> 
> ```
> OpenSurge: moteur de jeu rétro
> ```
> 
> This title has 30 characters.

Actually, it has 26 characters.

**Comment by Stilic** [comment]
> Maybe this?
> 
> ```
> OpenSurge: moteur de jeu rétro
> ```
> 
> This title has 30 characters.

I'm removing `rétro` from it then (keep in mind this will make the translation slightly less accurate).

**Comment by alemart** [comment]
> I'm removing `rétro` from it then (keep in mind this will make the translation slightly less accurate).

Let's not change the title.

Let's keep it `OpenSurge: moteur de jeu rétro` then.

**Comment by Stilic** [comment]
> > I'm removing `rétro` from it then (keep in mind this will make the translation slightly less accurate).
> 
> Let's not change the title.
> 
> Let's keep it `OpenSurge: moteur de jeu rétro` then.

Fixed it!

**Review by alemart — APPROVED** [review]
I put back the space before the colon, so that it looks correct: `OpenSurge : moteur de jeu rétro`. I'll check if F-Droid will really cut off the text, just to be sure. If it does, we change the title later.

Thank you!

**Comment by alemart** [comment]
Update: I'm correcting that 30-characters limit for the title. I think that it can be relaxed on F-Droid. I'm restoring the original title that you have submitted, with 32 characters.

**Pull request merged**
