### PR TITLE
Additional languages for the Android Metadata

### PR DESCRIPTION
**Pull request by SecularSteve**
Added: Dutch, German, British English, Bosnian, Serbian and Croatian.
Only things I did not touch were the images and changelogs.

### CODE REVIEW

**Review by alemart — CHANGES_REQUESTED** [review]
Hi @SecularSteve,

Add the translations that you maintain. No need to add en-GB, de-DE. Double check bs-BA, hr-HR, nl-NL and sr-RS.

Also keep in mind the limits I mentioned earlier:
* short_description.txt: max 80 chars. If translating is not possible, write an approximate translation that fits the limit
* title.txt: max 30 chars. If translating is not possible, leave it unstranslated

Thanks!

**Comment by SecularSteve** [comment]
Done...

**Comment by alemart** [comment]
Open Surge Engine and Surge the Rabbit are proper names. Why are they translated? They are displayed as is in the game:

Captura de tela_2024-05-22_19-15-00

**Comment by SecularSteve** [comment]
Switched them back to "Surge The Rabbit" in German and Dutch for consistency.

Kind of necessary to remain translated in the other languages though. Unless stated that a change is also required.

**Comment by SecularSteve** [comment]
Old habit. I apologise.

It's not really important in Dutch and German, but it's necessary in the other languages.

**Comment by alemart** [comment]
Are you using a machine translator such as DeepL and sending me that output?

I compared the words of your Dutch translation from fb0fa015d462d37b858cafe4ff3ecc81e1d2ad3a with those of DeepL and found a similarity score of over 94%. The texts are almost identical. The translations that are being sent by the other contributors score much lower.

Why is that, @SecularSteve?

[dutch-deepl.txt](https://github.com/alemart/opensurge/files/15419388/dutch-deepl.txt) [dutch-secularsteve.txt](https://github.com/alemart/opensurge/files/15419389/dutch-secularsteve.txt) [original.txt](https://github.com/alemart/opensurge/files/15419390/original.txt)

```sh
a=$(cat dutch-secularsteve.txt | sed "s/<\/\?b>/ /g" | sed "s/[!,.:]/ /g" | tr "[:upper:]" "[:lower:]" | sed "s/\s\+/\n/g" | grep . | sort | uniq)
b=$(cat dutch-deepl.txt | sed "s/<\/\?b>/ /g" | sed "s/[!,.:]/ /g" | tr "[:upper:]" "[:lower:]" | sed "s/\s\+/\n/g" | grep . | sort | uniq)
ab=$(comm -12 <(echo "$a") <(echo "$b"))
na=$(echo "$a" | wc -w)
nb=$(echo "$b" | wc -w)
nab=$(echo "$ab" | wc -w)
echo "100 * $nab / ($na + $nb - $nab)" | bc -l

94.64285714285714285714
```

---

> Kind of necessary to remain translated in the other languages though. Unless explicitly stated that a change is also required.

If that is the case, then why weren't they also translated in the game, in the other languages? How can this make sense?

**Comment by SecularSteve** [comment]
1. Coincidence, I assure you.
I've translated all of them word-for-word. Including the sentence variations. Maybe I was too literal.
If you doubt it, I'll try something more informal.

2. I'll change them too if it's that important. It's a "cultural" thing.

**Comment by alemart** [comment]
The text you have submitted is no better than that of a machine. Automatic translations cannot be relied on to sound natural to native speakers and to be of high quality.

When translators join the project, they read the [Translation Guide](https://wiki.opensurge2d.org/Translation_Guide), which states that automatic translations are not acceptable. If I accepted automatic translations, I would not have called humans for the job.

If you're using a machine translator for such a small piece of text, then perhaps you don't know these languages well enough.

I will not be accepting your translations.

> Coincidence, I assure you.

Nonsense. Similarity score of over 94%, same order of words. Deceptive answers are totally unacceptable.

> I'll change them too if it's that important. It's a "cultural" thing.

Nonsense. It's a sign of sloppy work, as was #96.

**Comment by SecularSteve** [comment]
Fine, forget it, I can't do this anymore...

I'm not a developer in any sort of way, and I'm deeply insecure, but now you've deeply offended me.

Forget about any contributions in the future if you can't even take my word over a machine trained by humans.

Have a nice day...

**Pull request closed without merging**
