### PR TITLE
Add German translation (UNTESTED!)

### PR DESCRIPTION
**Pull request by Wuzzy2**
This adds the German translation. It's based on the recently deleted file.

WARNING: This translation is currently UNTESTED because I have problems with compiling for now. For now, use this PR only for preview purposes. I'll come back to you when I managed to compile the game and test it.

### CODE REVIEW

**Review by alemart — CHANGES_REQUESTED** [review]
Nice to see you back, Wuzzy. I await your testing before merging the PR.

If it helps: in addition to compiling the source code, it's also possible to test the translation using the Snap/Flatpak versions available at [opensurge2d.org](https://opensurge2d.org).

**Comment by Wuzzy2** [comment]
Okay, I have manged to compile it again. And re-tested. Found a few typos and fixed them. The translation should be fine again now.

FYI: The following non-ASCII characters are used: äöüÄÖÜß
Also × (U+00D7, replaces the "x" in e.g. "5x5")
All of those seem to work for me. I'm sure that äöüÄÖÜß is OK. I wonder about ×.
Is the font shipped with the game? If yes, then I believe it should be OK.
Maybe consider using × instead x in English as well if it's OK. (but this is off-topic)

Note: If you want to see a nice diff, just use `diff` and compare the new file against the deleted one, since I used that one as a basis.

**Comment by Wuzzy2** [comment]
BTW, if you need me again, please open an issue about it and write “@Wuzzy2” in the text somewhere. This will trigger a GitHub notification for me. I usually react fast, I'm a translator of many games.
I think this GitHub notification might make sense to do with other translators as well, if they're on GitHub.

I think that deleting the entire translation was a little overkill if a translator has disappeared. Maybe instead move these files in a different directory for archival, so other translators can continue where others left. On the other hand, there's not a lot of strings so far, so it's not that big of a deal.

**Review by alemart — APPROVED** [review]
We currently ship Roboto with the game. These non-ASCII characters should work as long as we use UTF-8 in the translation files and as long as these particular strings are not rendered using bitmap fonts. Although many places use .ttf, the HUD uses the fonts/good_neighbors.png bitmap font, which is limited to a subset of ASCII.

It makes sense to use "×" instead of "x". I have updated the other translations accordingly.

I deleted the file: new contributors would not update the German translation, because the translation was already partially in place, with some strings missing. I could not get the translation updated either, because I could not reach out to you. I tried to contact you multiple times, to no avail (last time was before the 0.5.2 release). Deleting might be overkill, but it changes the situation one way or another. I'm glad that you're providing new contact information and that you're still interested in maintaining the German translation. This clears up the issue.

Thank you again for your contribution. Your nickname is back in the credits screen.

**Pull request merged**
