### PR TITLE
Added Croatian language

### PR DESCRIPTION
**Pull request by SecularSteve**
Almost the same as Bosnian and Serbian, but with key dialect differences.

### CODE REVIEW

**Review by alemart — CHANGES_REQUESTED** [review]
That is amazing, thanks!

How can the pause screen be fixed?

croatian

We probably need a TrueType font in the title screen?

**Comment by SecularSteve** [comment]
Yep, for all of them.

Just replace "IZAĐI" with either "IZADI" or "IZADJI'.

**Review by alemart — CHANGES_REQUESTED** [review]
Can you change PAUSE_RESTART so that it stays within the boundaries?

In addition, we have new characters in that smaller bitmap font, including common Cyrillic letters. Which new letters do you need to make your translations work without adaptations? Are these sufficient? čČćĆžŽđĐšŠ

good_neighbors

**Comment by SecularSteve** [comment]
Yes...

Done, fixed and restored for all three.

**Review by alemart — APPROVED** [review]
Thanks!

**Pull request merged**
